name: ApiVeritas Contract Tests (Mock Mode)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  contract-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: List files in repo root
        run: ls -la

      - name: Enable mock server mode in config.json
        run: |
          jq '.enableMockServer = true' src/config/config.json > temp && mv temp src/config/config.json

      - name: Build TypeScript
        run: npm run build

      - name: Download previous payloads artifact (if available)
        uses: actions/download-artifact@v4
        with:
          name: latest-payloads
          path: previous-payloads
        continue-on-error: true

      - name: Start Mock Server
        run: npm run start:mock &

      - name: List dist directory
        run: ls -R dist

      - name: Run ApiVeritas config
        run: npx apiveritas config

      - name: Run ApiVeritas tests and store new payloads
        run: npx apiveritas run --tests mock.json --testSuite mock

      - name: Compare with previous payloads (if available)
        run: |
          if [ -d "previous-payloads" ]; then
            echo "Running comparison with previous payloads..."
            npx apiveritas compare --testSuite mock
          else
            echo "No previous payloads found; skipping comparison."
          fi

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: apiveritas-report
          path: reports/
          retention-days: 3

