name: ApiVeritas Contract Tests (Mock Mode)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  contract-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Enable mock server mode in config.json
        run: |
          jq '.enableMockServer = true' src/config/config.json > temp && mv temp src/config/config.json

      - name: Build TypeScript
        run: npm run build

      # Download previous payloads *once*, restoring to the exact folder ApiVeritas expects
      - name: Download previous payloads artifact (if available)
        uses: actions/download-artifact@v4
        with:
          name: latest-payloads
          path: payloads
        continue-on-error: true

      - name: Start Mock Server
        run: npm run start:mock &

      - name: Run ApiVeritas config
        run: npx apiveritas config

      # Run tests, which create a new timestamped payload folder inside `payloads/`
      - name: Run ApiVeritas tests and store new payloads
        run: npx apiveritas test --tests mock.json

      # Run comparison only if at least 2 payload folders exist inside `payloads/`
      - name: Compare payloads
        run: |
          count=$(find payloads -mindepth 1 -maxdepth 1 -type d | wc -l)
          if [ "$count" -ge 2 ]; then
            echo "Found $count payload folders. Running comparison..."
            npx apiveritas compare --testSuite mock
          else
            echo "Only $count payload folder(s) found, skipping comparison."
          fi

      # Upload all payload folders including the new one for future runs
      - name: Upload payloads artifact
        uses: actions/upload-artifact@v4
        with:
          name: latest-payloads
          path: payloads/
          retention-days: 7

      # Upload the HTML report artifact as before
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: apiveritas-report
          path: reports/
          retention-days: 3
